const Icons = {
  Drawer : require('@assets/icons/ic_drawer.png'),
  Logo : require('@assets/icons/logo.png'),
  Search : require('@assets/icons/ic_search.png'),
  Cart : require('@assets/icons/ic_cart.png'),
  Deals : require('@assets/icons/ic_deals.png'),
  Favorite : require('@assets/icons/ic_favorite.png'),
  FavoriteSelected : require('@assets/icons/ic_favorite_selected.png'),
  Share : require('@assets/icons/ic_share.png'),
  Home : require('@assets/icons/ic_home.png'),
  User : require('@assets/icons/user.png'),
  Delete : require('@assets/icons/ic_delete.png'),
  EnFlag : require('@assets/icons/english.png'),
  ArFlag : require('@assets/icons/arabic.png'),
  Selected : require('@assets/icons/ic_selected.png'),
  Close : require('@assets/icons/ic_close.png'),
  UncheckCircle : require('@assets/icons/uncheck_circle.png'),
  CheckCircle : require('@assets/icons/check_circle.png'),
  DownArrow : require('@assets/icons/ic_down_arrow.png'),
  Address : require('@assets/icons/ic_address.png'),
  Shipping : require('@assets/icons/ic_shipping.png'),
  Star : require('@assets/icons/ic_star.png'),
  Language : require('@assets/icons/ic_language.png'),
  Feedback : require('@assets/icons/ic_feedback.png'),
  SignOut : require('@assets/icons/ic_sign_out.png'),
  Add : require('@assets/icons/ic_add.png'),
  Filter: require('@assets/icons/ic_filter.png'),
  SmallClose: require('@assets/icons/ic_small_close.png'),
  SliderMarker: require('@assets/icons/ic_slider_marker.png'),
  Cash: require('@assets/icons/ic_cash.png'),
  Bank: require('@assets/icons/ic_bank.png'),
  Money: require('@assets/icons/ic_money.png'),
}

export default Icons
