export const GET_ADMIN_TOKEN_PENDING = "GET_ADMIN_TOKEN_PENDING"
export const GET_ADMIN_TOKEN_SUCCESS = "GET_ADMIN_TOKEN_SUCCESS"
export const GET_ADMIN_TOKEN_FAIL = "GET_ADMIN_TOKEN_FAIL"

export const GET_CATEGORIES_PENDING = "GET_CATEGORIES_PENDING"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL"

export const GET_PRODUCTS_FOR_HOME_PENDING = "GET_PRODUCTS_FOR_HOME_PENDING"
export const GET_PRODUCTS_FOR_HOME_SUCCESS = "GET_PRODUCTS_FOR_HOME_SUCCESS"
export const GET_PRODUCTS_FOR_HOME_FAIL = "GET_PRODUCTS_FOR_HOME_FAIL"

export const GET_PRODUCTS_BY_CATEGORY_PENDING = "GET_PRODUCTS_BY_CATEGORY_PENDING"
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = "GET_PRODUCTS_BY_CATEGORY_SUCCESS"
export const GET_PRODUCTS_BY_CATEGORY_MORE = "GET_PRODUCTS_BY_CATEGORY_MORE"
export const GET_PRODUCTS_BY_CATEGORY_FAIL = "GET_PRODUCTS_BY_CATEGORY_FAIL"

export const GET_CHILD_CATEGORIES_INFO_PENDING = "GET_CHILD_CATEGORIES_INFO_PENDING"
export const GET_CHILD_CATEGORIES_INFO_SUCCESS = "GET_CHILD_CATEGORIES_INFO_SUCCESS"
export const GET_CHILD_CATEGORIES_INFO_FAIL = "GET_CHILD_CATEGORIES_INFO_FAIL"


export const SEARCH_PRODUCTS_PENDING = "SEARCH_PRODUCTS_PENDING"
export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS"
export const SEARCH_PRODUCTS_MORE = "SEARCH_PRODUCTS_MORE"
export const SEARCH_PRODUCTS_FAIL = "SEARCH_PRODUCTS_FAIL"

export const ADD_PRODUCT_TO_WISHLIST = "ADD_PRODUCT_TO_WISHLIST"
export const REMOVE_PRODUCT_TO_WISHLIST = "REMOVE_PRODUCT_TO_WISHLIST"

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART"
export const REMOVE_PRODUCT_TO_CART = "REMOVE_PRODUCT_TO_CART"
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY"

export const SIGN_UP_PENDING = "SIGN_UP_PENDING"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAIL = "SIGN_UP_FAIL"

export const SIGN_IN_PENDING = "SIGN_IN_PENDING"
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
export const SIGN_IN_FAIL = "SIGN_IN_FAIL"

export const GET_SHIPPING_METHODS_PENDING = "GET_SHIPPING_METHODS_PENDING"
export const GET_SHIPPING_METHODS_SUCCESS = "GET_SHIPPING_METHODS_SUCCESS"
export const GET_SHIPPING_METHODS_FAIL = "GET_SHIPPING_METHODS_FAIL"

export const GET_CUSTOMER_INFO_PENDING = "GET_CUSTOMER_INFO_PENDING"
export const GET_CUSTOMER_INFO_SUCCESS = "GET_CUSTOMER_INFO_SUCCESS"
export const GET_CUSTOMER_INFO_FAIL = "GET_CUSTOMER_INFO_FAIL"

export const CREATE_CART_PENDING = "CREATE_CART_PENDING"
export const CREATE_CART_SUCCESS = "CREATE_CART_SUCCESS"
export const CREATE_CART_FAIL = "CREATE_CART_FAIL"

export const ADD_ITEMS_TO_CART_PENDING = "ADD_ITEMS_TO_CART_PENDING"
export const ADD_ITEMS_TO_CART_SUCCESS = "ADD_ITEMS_TO_CART_SUCCESS"
export const ADD_ITEMS_TO_CART_FAIL = "ADD_ITEMS_TO_CART_FAIL"

export const SET_SHIPPING_INFO_PENDING = "SET_SHIPPING_INFO_PENDING"
export const SET_SHIPPING_INFO_SUCCESS = "SET_SHIPPING_INFO_SUCCESS"
export const SET_SHIPPING_INFO_FAIL = "SET_SHIPPING_INFO_FAIL"

export const CREATE_ORDER_PENDING = "CREATE_ORDER_PENDING"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"

export const SET_SHIPPING_ADDRESS = "SET_SHIPPING_ADDRESS"

export const SET_LANGUAGE = "SET_LANGUAGE"

export const SIGN_OUT = "SIGN_OUT"

export const SET_MY_ADDRESS = "SET_MY_ADDRESS"

export const GET_MY_ORDERS_PENDING = "GET_MY_ORDERS_PENDING"
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS"
export const GET_MY_ORDERS_FAIL = "GET_MY_ORDERS_FAIL"

export const APPLY_FILTER = 'APPLY_FILTER'

export const QUOTE_COUNTER = 'QUOTE_COUNTER'


export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'
export const GET_PROMOTION_CATEGORY_PENDING = 'GET_PROMOTION_CATEGORY_PENDING'
export const GET_PROMOTION_CATEGORY_SUCCESS = 'GET_PROMOTION_CATEGORY_SUCCESS'
export const GET_PROMOTION_CATEGORY_FAIL = 'GET_PROMOTION_CATEGORY_FAIL'
